server:
  port: 8762                    # 指定该Eureka实例的端口
spring:
  application:
    name: eureka-server
eureka:
  instance:
    hostname: backup         # 指定该Eureka实例的主机名
  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: http://admin:admin@127.0.0.1:8761/eureka/ #master 地址
security:
  basic:
    enabled: true
  user:
    name: admin
    password: admin