server:
  port: 8761                    # 指定该Eureka实例的端口
spring:
  application:
    name: eureka-server
eureka:
  instance:
    hostname: master         # 指定该Eureka实例的主机名
  client:
    fetch-registry: false
    serviceUrl:
      defaultZone: http://admin:admin@127.0.0.1:8762/eureka/ #backup地址
    register-with-eureka: false
security:
  basic:
    enabled: true
  user:
    name: admin
    password: admin